---
title: "logisitcreg"
output: html_document
---

```{r}
library(tidyverse)
library(cowplot)
theme_set(theme_cowplot())
```

```{r}
df = read_csv("/Users/admin/Desktop/320 DATA/movies_logistic_reg.csv")
```

```{r}
model_1 = glm(profitable ~., data=df, family="binomial")
summary(model_1)
```

```{r}
df2 = df %>% select(-41, -40, -38, -37)
```

```{r}
model_2 = glm(profitable ~ ., data=df2, family="binomial")
summary(model_2)
```

```{r}
df3 = df2 %>% select(-Matt_Damon, -Martin_Scorsese, -Woody_Allen, -CA, -FR, -DE)
```

```{r}
model_3 = glm(profitable ~ ., data=df3, family="binomial")
summary(model_3)
```

```{r}
df4 = df3 %>% select(-MGM)
```

```{r}
model_4 = glm(profitable ~ ., data=df4, family="binomial")
summary(model_4)
```

```{r}
df5 = df4 %>% select(-Foreign, -TV_Movie, -Music, -Family, -War, -Horror, -Thriller, -Mystery, -Western, -Action)
```

```{r}
model_5 = glm(profitable ~ ., data=df5, family="binomial")
summary(model_5)
```

```{r}
p1 = 
  data.frame(summary(model_5)$coefficients) %>% 
  rownames_to_column() %>% 
  select(-3, -4, -5) %>% 
  rename(name=1, val=2) %>% 
  ggplot(aes(reorder(name, val), val)) + 
  geom_bar(stat="identity", fill="#4B9CD3") + 
  coord_flip() +
  ggtitle("Value of Coefficient for Profitability in Best Logistic Model") +
  ylab("Log-Odds") + 
  xlab("Variable") +
  theme(plot.title = element_text(hjust=1.4))

p1

#ggsave("/Users/admin/Desktop/plots 320 FINAL/going foward/best_logistic_model.png", p1)
```


```{r}
df_genres = df %>% select(1:21)
```

```{r}
genres_only_model = glm(profitable ~ ., data=df_genres, family="binomial")
summary(genres_only_model)
```

```{r}
p2 =
  data.frame(summary(genres_only_model)$coefficients) %>% 
  rownames_to_column() %>% 
  rename(coef=2, SE=3, pval=5) %>% 
  select(-4) %>% 
  mutate(Significant = ifelse(pval <= 0.05, TRUE, FALSE)) %>% 
  mutate(hwr = coef + 1.96*SE, lwr = coef - 1.96*SE) %>% 
  select(-SE, -pval) %>% 
  mutate(rowname = replace(rowname, rowname=="TV_Movie", NA)) %>% 
  mutate(rowname = replace(rowname, rowname=="Foreign", NA)) %>% 
  na.omit() %>% 
  ggplot(aes(reorder(rowname, coef), coef, color=Significant)) + 
  geom_errorbar(aes(ymin=lwr, ymax=hwr)) +
  geom_point(aes(rowname, coef), size=0.5) +
  coord_flip() +
  scale_color_manual(values = c("red", "darkblue")) +
  ggtitle("95% Confidence Intervals for Coefficients Predicting Profitability in Genre Only Logistic Regression") +
  theme(plot.title = element_text(size=10, hjust=0.5)) +
  ylab("Coefficient Interval of Log-Odds") +
  xlab("Variable")

p2

#ggsave("/Users/admin/Desktop/plots 320 FINAL/better plots/p22.png", p2)
```

```{r}
movies = read_csv("/Users/admin/Desktop/320 DATA/movies_linear_reg.csv")
```

```{r}
library(lubridate)
options(scipen=999)
```

```{r, warning=F}
profit_over_time = 
  movies %>% select(budget, revenue, release_date) %>% 
  mutate(year = year(release_date)) %>% 
  mutate(profit = revenue - budget) %>% 
  mutate(profit_sm = profit / 1000000) %>% 
  select(-budget, -revenue, -release_date, -profit) %>% 
  group_by(year) %>% 
  summarize(mean_profit = mean(profit_sm)) %>% 
  filter(mean_profit > -20, mean_profit < 75) %>% 
  arrange(desc(year)) %>% slice(2:n()) %>% 
  ggplot(aes(year, mean_profit)) + geom_point(color="#c7c7c7") + 
  geom_smooth(method="lm", se=F, color="darkblue") +
  ggtitle("Average Profit of Movies by Year") +
  ylab("Profit (In Millions of 2017 USD)") + 
  xlab("Year") +
  theme(plot.title = element_text(hjust=0.5))

profit_over_time

#ggsave("/Users/admin/Desktop/plots 320 FINAL/better plots/profit_over_time.png", profit_over_time)
```

```{r}
mean(df5$profitable)
```


```{r}
p1 = 
  data.frame(summary(model_5)$coefficients) %>% 
  rownames_to_column() %>% 
  rename(coef=2, SE=3, pval=5) %>% 
  select(-4) %>% 
  mutate(hwr = coef + 1.96*SE, lwr = coef - 1.96*SE) %>% 
  select(-pval, -SE) %>% 
  ggplot(aes(reorder(rowname, coef), coef)) + 
  geom_errorbar(aes(ymin=lwr, ymax=hwr), color="darkblue") +
  geom_point(size=0.5, color="darkblue") +
  coord_flip() + 
  ggtitle("95% Confidence Intervals of Coefficients of Best Logistic Regression Model") +
  theme(plot.title = element_text(hjust=1.5, size=12)) +
  xlab("Variable") + 
  ylab("Coefficient Interval of Log-Odds")


p1

#ggsave("/Users/admin/Desktop/plots 320 FINAL/better plots/p111.png", p1)
```

```{r}
aics=
  c(
  summary(model_1)$aic,
  summary(model_2)$aic,
  summary(model_3)$aic,
  summary(model_4)$aic,
  summary(model_5)$aic)
```

```{r}
sequence = c(1, 2, 3, 4, 5)
models = c("Model 1", "Model 2", "Model 3", "Model 4", "Model 5")
```

```{r}
aics_plot =
  data.frame(aics, sequence) %>% cbind(models) %>% 
  ggplot(aes(reorder(models, sequence), aics)) + 
  geom_point(color = "darkblue") +
  geom_line(aes(sequence, aics), color="darkblue") + 
  ggtitle("Akaike Information Criterion (AIC) by Model") +
  xlab("Model Number (In Order From Full to Best Model)") +
  ylab("AIC")
```

```{r}
library(pscl)
```


```{r}
pR2s = c(
as.vector(pR2(model_1)[4]),
as.vector(pR2(model_2)[4]),
as.vector(pR2(model_3)[4]),
as.vector(pR2(model_4)[4]),
as.vector(pR2(model_5)[4]))
```

```{r}
pr2s_plot=
  data.frame(pR2s, sequence) %>% cbind(models) %>% 
  ggplot(aes(reorder(models, sequence), pR2s)) +
  geom_point(color="darkblue") +
  geom_line(aes(sequence, pR2s), color="darkblue") +
  ggtitle("McFadden's Pseudo R-Squared by Model") +
  xlab("Model Number (In Order From Full to Best Model)") +
  ylab("Pseudo R-Sq.")
```


```{r}
library(gridExtra)
```

```{r}
big_plot2 = grid.arrange(aics_plot, pr2s_plot)

ggsave("/Users/admin/Desktop/plots 320 FINAL/better plots/big_plot2.png", big_plot2)
```

```{r}

```

```{r}
get.RMSE = function(residuals){
  residuals_squared = (residuals)^(2)
  sum_residuals_squared = sum(residuals_squared)
  sum_residuals_squared_div_n = sum_residuals_squared / length(residuals)
  rooted_sum_residuals_squared_div_n = sqrt(sum_residuals_squared_div_n)
  return(rooted_sum_residuals_squared_div_n)
}
```


```{r}
RMSEs = c(
  get.RMSE(model_1$residuals),
  get.RMSE(model_2$residuals),
  get.RMSE(model_3$residuals),
  get.RMSE(model_4$residuals),
  get.RMSE(model_5$residuals))
```

```{r}
RMSE_plot_logi =
  data.frame(sequence, RMSEs) %>% cbind(models) %>% 
  ggplot(aes(reorder(models, sequence), RMSEs)) +
  geom_point(color="darkblue") +
  geom_line(aes(sequence, RMSEs), color="darkblue") +
  ggtitle("Root Mean Squared Error (RMSE) by Model") +
  xlab("Model Number (In Order From Full to Best Model)") +
  ylab("RMSE")
```

```{r}
big_plot3 = grid.arrange(aics_plot, pr2s_plot, RMSE_plot_logi)

big_plot3

ggsave("/Users/admin/Desktop/plots 320 FINAL/better plots/big_plot333.png", big_plot3)
```











